// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using project_kaupskra.Models;

#nullable disable

namespace project_kaupskra.Migrations
{
    [DbContext(typeof(FasteignakaupContext))]
    [Migration("20240318142223_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("project_kaupskra.Models.Fasteignakaup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("BRUNABOTAMAT_GILDANDI")
                        .HasColumnType("text");

                    b.Property<string>("BYGGAR")
                        .HasColumnType("text");

                    b.Property<decimal>("EINFLM")
                        .HasColumnType("numeric");

                    b.Property<int>("EMNR")
                        .HasColumnType("integer");

                    b.Property<int>("FAERSLUNUMER")
                        .HasColumnType("integer");

                    b.Property<int>("FASTEIGNAMAT")
                        .HasColumnType("integer");

                    b.Property<string>("FASTEIGNAMAT_GILDANDI")
                        .HasColumnType("text");

                    b.Property<int>("FASTNUM")
                        .HasColumnType("integer");

                    b.Property<string>("FEPILOG")
                        .HasColumnType("text");

                    b.Property<string>("FJHERB")
                        .HasColumnType("text");

                    b.Property<int>("FULLBUID")
                        .HasColumnType("integer");

                    b.Property<string>("HEIMILISFANG")
                        .HasColumnType("text");

                    b.Property<int>("HEINUM")
                        .HasColumnType("integer");

                    b.Property<int>("KAUPVERD")
                        .HasColumnType("integer");

                    b.Property<string>("LOD_FLM")
                        .HasColumnType("text");

                    b.Property<string>("LOD_FLMEIN")
                        .HasColumnType("text");

                    b.Property<int>("ONOTHAEFUR_SAMNINGUR")
                        .HasColumnType("integer");

                    b.Property<int>("POSTNR")
                        .HasColumnType("integer");

                    b.Property<string>("SKJALANUMER")
                        .HasColumnType("text");

                    b.Property<string>("SVEITARFELAG")
                        .HasColumnType("text");

                    b.Property<int>("SVFN")
                        .HasColumnType("integer");

                    b.Property<string>("TEGUND")
                        .HasColumnType("text");

                    b.Property<DateTime>("THINGLYSTDAGS")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UTGDAG")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("Fasteignakaup");
                });
#pragma warning restore 612, 618
        }
    }
}
